import Link from 'next/link'
import { ArrowRight, Search, CheckCircle2 } from 'lucide-react'
import { courses, CourseCard, Section, IconStats } from '../components/site'

export default function Home(){return <main>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Mahifxcapital Academy</span><h1>Learn Trading the Smart Way.</h1><p>Build real market knowledge, disciplined risk management and a repeatable trading process — from your first forex lesson to advanced market structure.</p><div className="hero-search"><Search size={19} color="#667085"/><input placeholder="What do you want to learn today?"/><button>Search</button></div><div className="hero-actions"><Link href="/courses" className="primary">Explore courses</Link><Link href="/courses/babypips" className="secondary">Start the Amharic School</Link></div></div><div className="hero-card"><div className="market-head"><b>EUR/USD</b><span>1.17342&nbsp; +0.42%</span></div><div className="big-chart"/><div className="market-head"><span>Market structure</span><span>Risk-first education</span></div></div></div></section>
<div className="container"><IconStats/></div>
<Section title="Featured courses" sub="Practical education designed around market skills, not hype."><div className="course-grid">{courses.map(c=><CourseCard key={c.id} c={c}/>)}</div></Section>
<section className="dark-band"><div className="container"><Section title="Students are viewing"><div className="course-grid">{courses.slice(1).concat(courses.slice(0,1)).map(c=><CourseCard key={'v'+c.id} c={c}/>)}</div></Section></div></section>
<Section title="Top categories" sub="Choose a learning path that matches your current stage."><div className="category-grid"><div className="category">Forex Fundamentals<small>8 courses</small></div><div className="category">Technical Analysis<small>11 courses</small></div><div className="category">Risk Management<small>6 courses</small></div><div className="category">Trading Psychology<small>5 courses</small></div></div></Section>
<section className="container instructor-banner"><div><h2>Teach on Mahifxcapital</h2><p>Share your market knowledge with serious learners across Ethiopia and beyond.</p></div><Link href="/instructor">Become an instructor</Link></section>
<Section title="What learners say" sub="Education should create clarity, not unrealistic promises."><div className="testimonial-grid"><div className="quote"><p>“The lessons are structured in a way that finally made risk management feel practical.”</p><b>— Dawit, Addis Ababa</b></div><div className="quote"><p>“I wanted Amharic-first forex education. The school format makes it easy to study lesson by lesson.”</p><b>— Hana, Ethiopia</b></div><div className="quote"><p>“The focus on process and journaling changed how I review my trades.”</p><b>— Samuel, Nairobi</b></div></div></Section>
<section className="section" style={{background:'#fff8e1'}}><div className="container" style={{textAlign:'center'}}><span className="eyebrow">Flagship course</span><h2 style={{fontSize:36}}>የባቢፒፕስ ትምህርት ቤት</h2><p style={{maxWidth:650,margin:'12px auto 24px',lineHeight:1.7}}>ከመጀመሪያ እስከ ባለሙያ — የፎረክስ መሰረቶችን፣ ትንተናን፣ አደጋ አስተዳደርንና የንግድ ስነ-ልቦናን በአማርኛ ይማሩ።</p><Link href="/courses/babypips" className="btn gold">ትምህርቱን ጀምር →</Link></div></section>
</main>}
